function actualiserPage(a){a=a.target;"button"===a.tagName.toLowerCase()||a.classList.contains("CTA")||location.reload()}window.addEventListener("scroll",function(){var a=document.querySelector(".navigation"),c=document.querySelector(".navigation.navigation-right"),b=document.querySelector("header").offsetHeight;window.pageYOffset>b?(a.classList.add("fixed"),c.classList.add("fixed")):(a.classList.remove("fixed"),c.classList.remove("fixed"))});
function showAdditionalImage(a){document.getElementById("additionalImage").style.backgroundImage="url("+a.src+")"}function afficherImage(a,c){var b=document.getElementById(a),g=document.querySelector(c),h=g.getAttribute("data-image-url"),f=g.getAttribute("data-background-url");h?b.src=h:b.style.display="none";g.style.backgroundImage=f?"url('"+f+"')":"none"}afficherImage("image_presentation",".cellule_presentation");afficherImage("image_pouvoir",".cellule_combat");
var factionData={"id-en-cours":{presentationUrl:"https://i.servimg.com/u/f88/18/85/03/67/1e141c10.jpg",combatUrl:"https://forum.xboxera.com/uploads/default/original/2X/7/709bd43b30ff1da6cf523b420b01b417bd2f9a11.gif",presentationAvatar:"https://i.servimg.com/u/f36/20/47/50/10/cesar_11.jpg",combatAvatar:"https://i.servimg.com/u/f36/20/47/50/10/b5357410.jpg",backgroundPosition:"center 60%"},"id-faction-1":{presentationUrl:"https://i.servimg.com/u/f88/18/85/03/67/5e42c212.jpg",combatUrl:"https://media.tenor.com/T1wrE0tbgjwAAAAd/soraka-healbank.gif",
presentationAvatar:"https://i.servimg.com/u/f36/20/47/50/10/julian11.jpg",combatAvatar:"https://i.servimg.com/u/f36/20/47/50/10/84174310.jpg",backgroundPosition:"center 20%"},"id-faction-2":{presentationUrl:"https://i.servimg.com/u/f36/20/47/50/10/52ebde10.png",combatUrl:"https://media.tenor.com/6EQy-Mczv0gAAAAC/swain-lol.gif",presentationAvatar:"https://i.servimg.com/u/f36/20/47/50/10/a443d110.jpg",combatAvatar:"https://i.servimg.com/u/f36/20/47/50/10/8406dc10.jpg",backgroundPosition:"center 20%"},
"id-faction-3":{presentationUrl:"https://i.servimg.com/u/f36/20/47/50/10/e211010.png",combatUrl:"https://64.media.tumblr.com/9ed8f2687c5f79344844d4d2b92f9776/88fd5a8036642eca-f2/s540x810/933fb6be6595f2dac79c5c3e3829b9734c85e70f.gif",presentationAvatar:"https://i.servimg.com/u/f36/20/47/50/10/19b73010.jpg",combatAvatar:"https://i.servimg.com/u/f36/20/47/50/10/thomas11.jpg",backgroundPosition:"center 20%"},"id-faction-4":{presentationUrl:"https://i.servimg.com/u/f36/20/47/50/10/e18db810.png",combatUrl:"https://i.redd.it/jduoixesyfw51.gif",
presentationAvatar:"https://i.servimg.com/u/f36/20/47/50/10/62876610.jpg",combatAvatar:"https://i.servimg.com/u/f36/20/47/50/10/45be9210.jpg",backgroundPosition:"center 20%"}},selectionCells=document.querySelectorAll("#id-en-cours, #id-faction-1, #id-faction-2, #id-faction-3, #id-faction-4");
function updateCells(a){var c=document.querySelector(".cellule_presentation"),b=document.querySelector(".cellule_combat");c.setAttribute("data-background-url",a.presentationUrl);c.setAttribute("data-image-url",a.presentationAvatar);c.style.backgroundImage="url('"+a.presentationUrl+"')";c.style.backgroundPosition=a.backgroundPosition;c.style.opacity="1";document.getElementById("image_presentation").src=a.presentationAvatar;b.setAttribute("data-background-url",a.combatUrl);b.setAttribute("data-image-url",
a.combatAvatar);b.style.backgroundImage="url('"+a.combatUrl+"')";b.style.backgroundPosition="top right";b.style.opacity="1";document.getElementById("image_pouvoir").src=a.combatAvatar}selectionCells.forEach(function(a){a.addEventListener("click",function(){updateCells(factionData[this.id])})});
document.addEventListener("DOMContentLoaded",function(){function a(e){document.querySelectorAll(".conteneur").forEach(function(d){d.classList.contains(e)?d.style.visibility="visible":d.style.visibility="hidden"});g.style.display="sonar-laconia"!==e?"block":"none"}function c(e,d){e.forEach(function(l,k){l.style.visibility=d?8>k?"visible":"hidden":8<=k?"visible":"hidden"})}var b=document.querySelectorAll(".sonar-1, .sonar-2, .sonar-3, .sonar-4, .sonar-5, .sonar-6, .sonar-7, .sonar-8, .sonar-saint-empire, .sonar-laconia, .sonar-erobern, .sonar-llygredd, .sonar-khidesh, .sonar-lontemar, .sonar-maur-olosta"),
g=document.querySelector(".categorie"),h={"sonar-1":"neshraun","sonar-2":"ker-vashterion","sonar-3":"althela","sonar-4":"saint-empire","sonar-5":"matergabia","sonar-6":"paracelse","sonar-7":"kerma","sonar-8":"dar-es-balat","sonar-saint-empire":"saint-empire","sonar-laconia":"saint-empire-laconia","sonar-erobern":"saint-empire-erobern","sonar-llygredd":"saint-empire-llygredd","sonar-khidesh":"saint-empire-khidesh","sonar-lontemar":"saint-empire-lontemar","sonar-maur-olosta":"saint-empire-maur-olosta"};
c(b,!0);var f=document.querySelector(".actualiser-button");f.addEventListener("click",function(){a("accueil");c(b,!0);f.style.visibility="hidden";currentSonar=null});b.forEach(function(e){e.addEventListener("click",function(){var d=e.classList[0];a(h[d]);"sonar-4"===d||"sonar-saint-empire"===d||"sonar-laconia"===d||"sonar-erobern"===d||"sonar-llygredd"===d||"sonar-khidesh"===d||"sonar-lontemar"===d||"sonar-maur-olosta"===d?c(b,!1):c(b,!0);f.style.visibility="visible"})})});